CREATE TABLE SUCURSALES(
    suc_nombre VARCHAR(50) NOT NULL,
    suc_ciudad VARCHAR(50) NOT NULL,
    PRIMARY KEY(suc_nombre)
) ENGINE=InnoDB;

CREATE TABLE CUENTAS(
    cue_numero INT NOT NULL,
    cue_saldo DECIMAL(10, 2) NOT NULL,
    suc_nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY(cue_numero),
    FOREIGN KEY(suc_nombre) REFERENCES SUCURSALES(suc_nombre)
) ENGINE=InnoDB;

CREATE TABLE PRESTAMOS(
    pre_numero INT NOT NULL,
    pre_valor DECIMAL(10, 2) NOT NULL,
    suc_nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY(pre_numero),
    FOREIGN KEY(suc_nombre) REFERENCES SUCURSALES(suc_nombre)
) ENGINE=InnoDB;

CREATE TABLE CLIENTES(
    cli_nombre VARCHAR(50) NOT NULL,
    cli_direccion VARCHAR(50) NOT NULL,
    cli_ciudad VARCHAR(50) NOT NULL,
    PRIMARY KEY(cli_nombre)
) ENGINE=InnoDB;

CREATE TABLE IMPOSITOR(
    cue_numero INT NOT NULL,
    cli_nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY(cue_numero, cli_nombre)
) ENGINE=InnoDB;

CREATE TABLE PRESTATARIO(
    pre_numero INT NOT NULL,
    cli_nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY(pre_numero, cli_nombre)
) ENGINE=InnoDB;

CREATE TABLE TIPO_DOCUMENTO(
    TDC_ID VARCHAR(2) NOT NULL,
    TDC_NOMBRE VARCHAR(20) NOT NULL,
    TDC_ESTADO INT NOT NULL,
    PRIMARY KEY(TDC_ID)
) ENGINE=InnoDB;

CREATE TABLE AFILIADO(
    AFI_ID VARCHAR(10) NOT NULL,
    AFI_NOMBRE VARCHAR(20) NOT NULL,
    AFI_APELLIDOS VARCHAR(30) NOT NULL,
    TDC_ID VARCHAR(2) NOT NULL,
    AFI_DOCUMENTO VARCHAR(20) NOT NULL,
    AFI_TELEFONO VARCHAR(20) NOT NULL,
    AFI_DIRECCION VARCHAR(30) NOT NULL,
    AFI_EMAIL VARCHAR(30) NOT NULL,
    AFI_ESTADO INT NOT NULL,
    PRIMARY KEY(AFI_ID),
    FOREIGN KEY(TDC_ID) REFERENCES TIPO_DOCUMENTO(TDC_ID)
) ENGINE=InnoDB;

CREATE TABLE PLAN(
    PLN_ID VARCHAR(4) NOT NULL,
    PLN_NOMBRE VARCHAR(15) NOT NULL,
    PLN_FECHA_INICIO DATE NOT NULL,
    PLN_FECHA_FIN DATE NOT NULL,
    PLN_ESTADO INT NOT NULL,
    PRIMARY KEY(PLN_ID)
) ENGINE=InnoDB;

CREATE TABLE CONTRATO(
    CTO_ID VARCHAR(20) NOT NULL,
    AFI_ID VARCHAR(10) NOT NULL,
    PLN_ID VARCHAR(4) NOT NULL,
    CTO_CANTIDAD_USUARIOS INT NOT NULL,
    CTO_FECHA_INICIO DATE NOT NULL,
    CTO_FECHA_RETIRO DATE NOT NULL,
    CTO_FECHA_REGISTRO DATE NOT NULL,
    CTO_EPS VARCHAR(20) NOT NULL,
    PRIMARY KEY(CTO_ID),
    FOREIGN KEY(AFI_ID) REFERENCES AFILIADO(AFI_ID),
    FOREIGN KEY(PLN_ID) REFERENCES PLAN(PLN_ID)
) ENGINE=InnoDB;
